version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Root directory of your project
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      # Ignore specific versions or ranges if needed
    allow:
      - dependency-type: "all"

    # Optionally, group updates by type or scope
    groups:
      javafx:
        patterns:
          - "org.openjfx:*"
      junit:
        patterns:
          - "org.junit.jupiter:*"
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"

    # Optionally, set labels for PRs
    labels:
      - "dependencies"
